spring:
  datasource:
    url: jdbc:mysql://${DATASOURCE_HOST:localhost}:${DATASOURCE_HOST:3306}/${DATASOURCE_NAME:nt_test}?createDatabaseIfNotExist=true
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}